"""Markdown rendering for openclaw-output-vetter scan results."""
from __future__ import annotations

from openclaw_output_vetter_mcp.types import (
    ActionOutcomeReport,
    GroundingResult,
    SwallowedExceptionReport,
    Verdict,
)


def _verdict_emoji(v: Verdict) -> str:
    if v == Verdict.FABRICATED:
        return "🛑"
    if v == Verdict.PARTIALLY_GROUNDED:
        return "⚠"
    if v == Verdict.CLEAN:
        return "✓"
    return "?"


def _verdict_label(v: Verdict) -> str:
    return f"{_verdict_emoji(v)} {v.value.upper()}"


def render_grounding(*, label: str, result: GroundingResult) -> list[str]:
    lines = [f"**{label}** — {_verdict_label(result.verdict)}"]
    lines.append(
        f"  · {result.grounded_count}/{result.total_claims} claim(s) grounded "
        f"(score {result.overall_grounding_score:.2f})"
    )
    if result.summary:
        lines.append(f"  · {result.summary[:160]}{'…' if len(result.summary) > 160 else ''}")
    return lines


def render_swallowed_exceptions(*, label: str, report: SwallowedExceptionReport) -> list[str]:
    lines = [f"**{label}** — {_verdict_label(report.verdict)}"]
    lines.append(f"  · {report.finding_count} finding(s)")
    for f in report.findings[:3]:
        lines.append(
            f"  - line {f.line_number}: `{f.pattern}` ({f.severity.value}) — {f.description}"
        )
    return lines


def render_action_outcome(*, label: str, report: ActionOutcomeReport) -> list[str]:
    lines = [f"**{label}** — {_verdict_label(report.verdict)}"]
    lines.append(f"  · {report.mismatched_count} mismatch(es)")
    for mm in report.mismatches[:3]:
        lines.append(
            f"  - `{mm.rule_id}` ({mm.severity.value}): {mm.description}"
        )
        lines.append(f"    - expected: {mm.expected}")
        lines.append(f"    - actual: {mm.actual}")
    return lines


def render_output_vet_report(
    *,
    grounding_cases: list[tuple[str, GroundingResult]],
    swallowed_cases: list[tuple[str, SwallowedExceptionReport]],
    outcome_cases: list[tuple[str, ActionOutcomeReport]],
    version: str,
) -> str:
    """Render a multi-scanner verification report as markdown."""
    lines: list[str] = []
    lines.append("## openclaw-output-vetter · agent claim verification report")
    lines.append("")

    total = len(grounding_cases) + len(swallowed_cases) + len(outcome_cases)
    lines.append(f"**Cases vetted:** {total}  ·  3 scanner kinds: grounding, swallowed-exceptions, action-outcome")
    lines.append("")

    if grounding_cases:
        lines.append("### Grounding (RAG / context-fidelity)")
        lines.append("")
        for label, result in grounding_cases:
            lines.extend(render_grounding(label=label, result=result))
            lines.append("")

    if swallowed_cases:
        lines.append("### Swallowed exceptions (agent-written code)")
        lines.append("")
        for label, report in swallowed_cases:
            lines.extend(render_swallowed_exceptions(label=label, report=report))
            lines.append("")

    if outcome_cases:
        lines.append("### Action outcome (claim vs before/after diff)")
        lines.append("")
        for label, report in outcome_cases:
            lines.extend(render_action_outcome(label=label, report=report))
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        f"> ℹ Generated by `openclaw-output-vetter-mcp-report` v{version}. "
        f"Pipe inputs via stdin or invoke as an MCP server in Claude Code / Cursor / OpenClaw "
        f"via `verify_response_grounding`, `find_swallowed_exceptions`, or `verify_action_outcome`."
    )

    return "\n".join(lines)
